### ISSUE TITLE
Cannot use the images inserted in the markdown file

### ISSUE THREAD

**Issue by meicale** [abeleinin/vimdoc#2]

**Comment by abeleinin** [comment]
I added documentation for using fonts and images to the README. Let me know if that clarifies the problem you were having and if you have any other issues feel free to ask. I'm glad you enjoy the plugin!

**Comment by meicale** [comment]
Thanks for your reply, it is kind for you to update the readme.md.
But, I think I know how to add a figure file into md file, use other tools(VSCode) can preview it and convert it directly to pdf using pandoc, it works, too. The source code:
![image](https://user-images.githubusercontent.com/2771499/228409986-a96be80b-6ffc-40ed-bead-05dfabee9ec4.png)
The generated pdf by this plugin:
![image](https://user-images.githubusercontent.com/2771499/228410260-f0d70a89-cf2a-404d-ad96-928e66cfafdf.png)
The pdf generated directly by pandoc:
![image](https://user-images.githubusercontent.com/2771499/228412115-fe4eed89-2aa7-4a69-8b4d-144c763f1fe8.png)
It can just have the captions of the image, but not the image itself. I think it is caused by the directory problem, the inserted relative path of the image is relative to the current md file. So I have to the use the pandoc command in that directory. 

Thank you again!

**Comment by meicale** [comment]
I will close this issue since this problem does not caused by this plugin. Maybe, something used to specify the cwd of neovim or this plugin may help.  Thx!
